### ISSUE TITLE
Typing single % sign causes app to hang

### ISSUE THREAD

**Issue by adamfowleruk** [humdingerb/quicklaunch#22]
I was playing around with quicklaunch before reading the documentation (!), and was testing various wildcards. I typed a single % character in. All of a sudden, the app hangs, CPU on one core spikes to 100%, and I had to quit using shft + ctr + alt + click the app on the deskbar.

Haiku build 52346. Quicklaunch 1.2-4.

**Comment by humdingerb** [comment]
Thanks, fixed with the latest change.

**Comment by humdingerb** [comment]
Oh, and when you don't have any favourites set, e.g. when you start Quicklaunch for the first time,   it tells you that "*" can be used as wildcard... Just saying... :)

**Comment by adamfowleruk** [comment]
Yeah I know, and I used that first, but then I got interested in what else I could type and just started experimenting... 8o)

**Comment by humdingerb** [comment]
And I'm grateful for that! After all, Quicklaunch would have fallen on its face it you'd look for something like some whacky statistics app named "5th%ile". :)
