### ISSUE TITLE
Add shortcut option to setup

### ISSUE THREAD

**Issue by deejam** [humdingerb/quicklaunch#23]
Add option to create an application shortcut to start QuickLaunch and what keys to use. Currently, this has do be performed manually. It should probably be enabled by default, as launching QuickLaunch manually defeats its purpose.

**Comment by humdingerb** [comment]
I didn't see the need for re-implementing this in the Quicklaunch settings, when there's a systemwide preference panel for that. I may add a link to open the Shortcuts prefs, we'll see...

**Comment by probonopd** [comment]
Awesome tool, makes me much more productive on Haiku.

> I didn't see the need for re-implementing this in the Quicklaunch settings, when there's a systemwide preference panel for that

Doing it in the Shortcuts settings is cumbersome. I would bet that most users don't know what to enter under "application", namely `/boot/system/apps/QuickLaunch/QuickLaunch` (just `QuickLaunch` doesn't cut it!).

**Comment by diversys** [comment]
> But actually the best solution would be if this came pre-installed and pre-configured in the default Haiku installation.

Indeed, there is a ticket about that https://dev.haiku-os.org/ticket/14841

**Comment by humdingerb** [comment]
> Doing it in the Shortcuts settings is cumbersome. I would bet that most users don't know what to enter under "application", namely `/boot/system/apps/QuickLaunch/QuickLaunch` (just `QuickLaunch` doesn't cut it!).

Yeah, the Shortcuts prefs have been in need of an overhaul for many years (decades really, if we go back to its origin "SpiceyKeys"). :)
It does use a file dialog to help find the app to shortcut to, so it's not that hard to do.

**Comment by diversys** [comment]
Actually, there is no file dialog in Shortcuts anymore.

**Comment by diversys** [comment]
Oh, Actually there is a file dialog there is you right click a list in Application column. I think double click there should open it instead of this tiny window.

![image](https://user-images.githubusercontent.com/1316513/61031039-616f1500-a3c7-11e9-824b-8fc8d91b96cc.png)

**Comment by humdingerb** [comment]
Agreed. As said, the Shortcuts prefs would be a prime target for changes... :)

**Comment by probonopd** [comment]
>  Actually there is a file dialog there is you right click a list in Application colum

No one is gonna find that ;-)

**Comment by KevinAdams05** [comment]
> 
> 
> > Actually there is a file dialog there is you right click a list in Application colum
> 
> No one is gonna find that ;-)

Yep, I never knew that was there!! I always wondered why the box was so small, and there was (apparently) no file dialog.

**Comment by humdingerb** [comment]
Really? Haiku's ubiquitous use of context menus has me right-clicking any objects on any OS/in any app right away...
