### ISSUE TITLE
Main listview has a scrollbar if 2 items are found

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#36]

**Comment by humdingerb** [comment]
You mean the window isn't high enough for two items and therefore the scrollbar is active?
I've only seen that on 64bit Haiku and never found out why... Thought there was a ticket for that already, but apparently there isn't.

**Comment by diversys** [comment]
Yes, that's what I see. I'm on 32bit Haiku though.

**Comment by humdingerb** [comment]
Curious. Can't seem to replicate... even with different font sizes. I tried just having 2 favourites and keep adding letters until only 2 results were left.
Can you provide a step-by-step that shows it.

**Comment by diversys** [comment]
Interestingly, I can reproduce it with Qt Configurator + Qt Creator but not with Terminal + TextSearch. Maybe icon heights adds a few pixels somehow?

**Comment by humdingerb** [comment]
This may be fixed in latest release v1.6.

**Comment by diversys** [comment]
Still here.

**Comment by humdingerb** [comment]
I don't have Qt Creator installed, but maybe I'll find another pair of apps tat trigger it. What font and font size do you use?

**Comment by diversys** [comment]
Default font, 12pt.

**Comment by lonemadmax** [comment]
I can also get it with Terminal + TextSearch, with a twist. With "te" I get two copies of them (installed and compiled), and also TelnetService. continue typing to filter just the terminal entries and all is well. Now delete characters back to "te" and continue again to "terminal". Each character typed changes the height two pixels back and forth, making the list height 83 or 85, with an item height of 42.
