### ISSUE TITLE
Fails opening app when run from keyboard shortcut

### ISSUE THREAD

**Issue by phw** [humdingerb/quicklaunch#37]
I have a strange issue with QuickLaunch. I have setup a keyboard shortcut to launch `/boot/system/apps/QuickLaunch/QuickLaunch` on Option+Space.

This works in general, but I cannot open the app [Picard](https://depot.haiku-os.org/picard) installed from Haiku Depot. However, if I start QuickLaunch from the terminal or the deskbar launching Picard works just fine.

I tried to debug this to see what kind of error happens, but since it works when starting QuickLaunch from terminal or via debugger it is rather difficult to see any error causes.

**Comment by diversys** [comment]
See #15.

**Comment by phw** [comment]
Thanks, closing this then as a duplicate.
