### ISSUE TITLE
Implement drag'n'drop support for ignore list

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#4]

**Comment by humdingerb** [comment]
263808f addresses part of this. Drag&drop from Tracker works, but I shy away from drag&drop from the main window's result list... :)

**Comment by humdingerb** [comment]
Implemented drag&drop after all as I could leverage code already done for BurnItNow and Clippdinger with ade4de4.
You can drag from Tracker or an item from the main window list.
