### ISSUE TITLE
Scale icon in Deskbar

### ISSUE THREAD

**Issue by diversys** [humdingerb/quicklaunch#42]
Currently QL deskbar icon doesn't scale when large font is used.

**Comment by humdingerb** [comment]
This was already addressed in 2fece22178c52818e1f45f3624ac374c924f0812.

I'll have to check if it all works on beta3, too. Otherwise I'll have to wait for beta4 for a QuickLaunch update.

**Comment by humdingerb** [comment]
Forgot to close this issue, it seems... Works with beta5.
