### ISSUE TITLE
Numpad doesn't work in searchfield

### ISSUE THREAD

**Issue by Briseur** [humdingerb/quicklaunch#43]
I tried to launch 2048 from QuickLaunch. It works only if I use shift+'char above the letters'. If I try to use numbers from the numpad  most of the numbers are mute. I only get 0,4,5 & 6. This is using a generic 105 keys keyboard and FR keymap, on nightly hrev56386.
In other places, like on terminal, I get all numbers normally.

**Comment by humdingerb** [comment]
Thanks, it's fixed.
