### ISSUE TITLE
Avoid placing the Settings dialog "always on top"

### ISSUE THREAD

**Issue by OscarL** [humdingerb/quicklaunch#55]
I'm trying to add a path to the "Ignore list", and when hitting the "Add" button, the open dialog gets obscured by the Settings' window.

(fresh install of QuickLaunch on beta5 64 bits)

**Comment by humdingerb** [comment]
Yeah, it's all a bit complicated, managing the change of "feel" of windows.
* I want the main window to be normally on top of all else, but allow user interaction with the other windows.
* When the Settings window is open, I want that on on top of the main window.
* The file dialog OTOH should be on top of Settings and Main window, but only for as long as it's open.

I'll keep it in mind, but it's on the back-burner. Normally there should be enough space to move the obscuring Settings window out of the way while using the file dialog. Not ideal, but it's not an action one does regularly. :)
