### ISSUE TITLE
Add an option to only query on the boot disk.

### ISSUE THREAD

**Issue by OscarL** [humdingerb/quicklaunch#56]
I have a lot of partitions/installs, having to add them manually to the ignore list is a bit on the PITA side, when my use case for QuickLaunch is 100% of the time to look for apps on the boot volume.

Perhaps a more general solution would be to have both ignore and include lists for locations to query?

As always, thanks for QL!

**Comment by humdingerb** [comment]
Having two lists does feel like complicating things.
I'll look into allowing to select multiple files in the ignore file dialog. The you can navigate to "Disks" and select all but /boot and add them in one go.

**Comment by humdingerb** [comment]
Hang on... the file panel already accepts multiple selections. :)
Good enough?
