### ISSUE TITLE
Request: single click to open

### ISSUE THREAD

**Issue by Perelandra0x309** [humdingerb/quicklaunch#9]
Could you enable (or provide an option in Setup) so a single mouse click opens an application in the list?

**Comment by humdingerb** [comment]
Probably. :)

**Comment by humdingerb** [comment]
Added with da60544 and following.

**Comment by Perelandra0x309** [comment]
Woohoo!  Added as an option! :-)

**Comment by humdingerb** [comment]
yeah, since 50% of the users that replied to my poll in the forums said so... :)
